### ISSUE TITLE
support for independent channels

### ISSUE THREAD

**Issue by hayguen** [dbry/audio-stretch#6]
usually, there's just one single signal source - even when recorded stereo in 2 channels.
thus i assume, it's ok to sum both channels and search for the pitch afterwards. that does implicitly save cpu power.

in case, the channels are completely independent and might speak at same time (sort of crosstalk) .. i would assume, the stretching quality is degraded, right?
if this is the case, it would be beneficial to have an option to process (and buffer the results) independently.

**Comment by dbry** [comment]
@hayguen Yes, you are correct that if the channels are independent (like two voices panned left and right) then this method of combining the channels would not sound good. Similarly, processing the channels independently would not sound good for a single centered voice (unless the channels were _exactly_ identical). Ideally, it would be possible to guess which was better based on the period calculations, but barring that I agree it would be nice to have manual control over the selection.

The reason I did not make this part of the library is that I believe that it makes more sense to implement independent stereo channels on the client side by simply spinning up two instances of the stretching code. Note that the way stereo is currently handled (periods calculated on mono version but applied to both channels) would _not be possible_ to do on the client side, which is why it's implemented that way in the library.

If you think it would be useful I can take a look and see how hard it would be to do a demo version in the client, but it should be pretty obvious how to do it.

**Comment by hayguen** [comment]
@dbry : sure, implementation should be pretty obvious. I was slightly unsure, how independent channels should get processed, to yield best quality. a note in the code would be nice.
