### ISSUE TITLE
different ratio for silent sections

### ISSUE THREAD

**Issue by hayguen** [dbry/audio-stretch#9]
stumbled over the chrome plugin skip-silence, see https://github.com/vantezzen/skip-silence , which is a very interesting idea.
it allows to configure different speeds for (non) silent sections .. and a threshold for the silence detection.

a good (automatic) silence detection might get complicated. the manual threshold should be simple.
for futher simplicity, a preprocessing module might zero the "silent" sections, that the already existing zero-detector can be used ..

**Comment by dbry** [comment]
@hayguen I just pushed an experimental version that includes silence detection and allows a different stretch ratio to be applied to those segments, and it works really well! I have found in many voice samples you can cut 20% by just reducing the silence to 0.25x. There were artifacts at first because the silence processing would creep into the surrounding voice, but I eliminated this by requiring both the previous and next block to measure as silence also. Let me know what you think...

**Comment by hayguen** [comment]
@dbry : now looking at your patch. i haven't really tested it. just looked over the sources:

in my mind was, amending the `stretch_samples()`, that both ratios (`ratio` and `silent_ratio`) are passed as parameters
* and herein, use the special case of `(sum == 0)` in the `find_period()` and `find_period_fast()` functions to detect silence
* and probably add an additional parameter and element in `struct stretch_cnxt` to delay using `silent_ratio` until N samples of silence are passed
* in the "silent" path, any ratio - not limited to 0.25 - could be used - just delivering zeros. but this might be an additional option
* further on, check against a `silence_threshold` (not in `dB`) utilizing `rms_level_dB()` could be achieved also, by comparing against the `sum` in the `find_period()` functions. the `sum` should be quite comparable to the rms

would think, that my approach would save CPU, for the additional calculation of `rms_level_dB()` and also .. would offer a much simpler usage.
probably offer an additional function `stretch_samples_ex()` with the additional parameters .. and keep the existing `stretch_samples()` as a simple wrapper.

i could try to implement this ..?

**Comment by hayguen** [comment]
see branch https://github.com/hayguen/audio-stretch/tree/alt_silent_ratio for a first untested implementation ..
for sure, it needs some testing .. and some tweaking

**Comment by dbry** [comment]
@hayguen I think that what you suggest could work very well, but I also see some possible problems. One is that if there is background noise then the silence segments will sound out of place being completely silent. For the best quality I think it's a good idea to avoid discontinuities and simply change the ratio when silence is detected.

Having the detection code outside the stretch library (like I prototyped) was done for convenience and could be moved into it if it's successful and it might make sense to combine the silence detection and the stretch period, but the CPU to detect the level is trivial and I had to use "look-ahead" to avoid artifacts.

Unfortunately, I am not being paid for this work (not sure about you) and have worked far more on this already than I can afford. I believe that I will finish up the prototype I have (which works very well) and move on to other projects. Obviously you are welcome to try implementing anything you like (this is FOSS!) but at this point I think it makes more sense for you to fork the repository because I simply cannot spend any more time and thought on it.

Thanks for all you help and suggestions!

**Comment by hayguen** [comment]
@dbry

> if there is background noise then the silence segments will sound out of place being completely silent

yes, this might be the case .. but it depends on the scenario, if this is an issue at all:
i have in mind, putting the stretcher (in unknown/far future) into an SDR (software defined radio) program - behind the noise squelch, which would have zeroed the background noise anyway.

but, i could stretch the samples - as in the non-silent case - when `silent_ratio >= 0.25` ..
or simply copy the amount of samples - in hope, the incontinuity isn't perceivable.



> detection code outside the stretch library (like I prototyped) was done for convenience and could be moved into it ..

don't think, that this is necessary. it might stay in main - as sort of example.


> the CPU to detect the level is trivial and I had to use "look-ahead" to avoid artifacts.

suppose, that the look-ahead is necessary, cause of the unprocessed samples in `stretch_cnxt::inbuff[]`.
hmm, yes, you might be right, cause at the input, you don't need to test for multiple periods, which is the cpu intensive part. thus, rms calculation is kind of linear. i hadn't considered this.


> I am not being paid for this work (not sure about you) ..

the company i work for .. already integrated the library: a colleague already had implemented cascading (outside).
when i had a look, i realized, that it looks improvable (independent channels) - and afterwards created the issue(s) here.
but i'm also not paid for changes or enhancements. i'm doing the work outside work.
i personally listen to lots of podcasts and audio (of videos from youtube and other platforms) .. thus, i personally prefer saving time :-)


> have worked far more on this already than I can afford. I believe that I will finish up the prototype I have (which works very well) and move on to other projects

this is absolutely fair - as this is FOSS, as you state.
would you consider a pull request for a finalized version of https://github.com/hayguen/audio-stretch/tree/alt_silent_ratio , on top of your final work?

Anyway: Big Thanks for your help and work!

**Comment by dbry** [comment]
> 
> this is absolutely fair - as this is FOSS, as you state. would you consider a pull request for a finalized version of https://github.com/hayguen/audio-stretch/tree/alt_silent_ratio , on top of your final work?
> 

@hayguen I have been playing with my version and am very happy with the results and think it might be confusing to have two implementations of silence handling in the same program. That said, I am happy to take a look and try out what you come up with. Thanks!

**Comment by hayguen** [comment]
@dbry  meanwhile tested the updates master:
congrats - it sounds really good!

it sounds much better, than the initial inspiration https://github.com/vantezzen/skip-silence

**Comment by dbry** [comment]
> @dbry meanwhile tested the updates master: congrats - it sounds really good!
> 
> it sounds much better, than the initial inspiration https://github.com/vantezzen/skip-silence

@hayguen Glad to hear it! And thanks for the suggestion, I don't think it would have occurred to me otherwise to add silence detection to this tool.
